version: '3'

services: 
  api_gateway_service:
    build:
      context: ./api_gateway_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000    
    ports:
      - "8000:8000" 
    depends_on:
      - summarize_service

  summarize_service:
    build:
      context: ./summarize_service 
    command: uvicorn main:app --host 0.0.0.0 --port 8001 
    ports:
      - "8001:8001"
    